scrum/src/main/java/scrum/entities/Game.java
package scrum.entities;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Game {
	@Id private int id;
	private String user;
	private int points;
	private int level;
	private Date date;
	private int rank;
	
	public Game() {
	}
	
	public Game(String user, int points, int level, Date date) {
		this.user = user;
		this.points = points;
		this.level = level;
		this.date = date;
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	public int getPoints() {
		return points;
	}
	public void setPoints(int points) {
		this.points = points;
	}
	public int getLevel() {
		return level;
	}
	public void setLevel(int level) {
		this.level = level;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public int getRank() {
		return rank;
	}
	public void setRank(int rank) {
		this.rank = rank;
	}
	
	
	
	
	
}

scrum/src/main/java/scrum/model/Block.java
package scrum.model;

import java.util.ArrayList;
import java.util.List;

public class Block {
	public static final int TOP = 0;
	public static final int RIGHT = 1;
	public static final int BOTTOM = 2;
	public static final int LEFT = 3;
	
	private Colour colour;
	private List<Block> neighbours;
	
	public Block(Colour colour){
		this.colour = colour;
		initNeighbours();
	}
	
	private void initNeighbours(){
		this.neighbours = new ArrayList<Block>();
		for (int i = 0; i < 4; i++) {
			this.neighbours.add(null);
		}		
	}
	
	public void clearNeighbours(){
		for (int i = 0; i < 4; i++) {
			this.neighbours.set(i, null);
		}
	}
	
	public boolean isClickable(){
		if(colour == Colour.TRANSPARENT){
			return false;
		}
		for (Block neighbour : neighbours) {
			if (neighbour != null && colour == neighbour.colour){
				return true;
			}				
		}
		return false;
	}
	

	public Colour getColour() {
		return colour;
	}

	public List<Block> getNeighbours() {
		return neighbours;
	}

	public void setColour(Colour colour) {
		this.colour = colour;
	}
	
	
}

scrum/src/main/java/scrum/model/Board.java
package scrum.model;

import java.util.List;


public class Board {
	public static final  int BOARDWIDTH = 20;
	public static final int BOARDLENGTH = BOARDWIDTH*BOARDWIDTH;
	public static final int TOTOP = -Board.BOARDWIDTH;
	public static final int TORIGHT = 1;
	public static final int TOBOTTOM = Board.BOARDWIDTH;
	public static final int TOLEFT = -1;
	
	private List<Block> blockTable;
	
	public Board() {
		
	}
	
	
// *********************************************************	
//	Getters and Setters
	public List<Block> getBlockTable() {
		return blockTable;
	}

	public void setBlockTable(List<Block> blockTable) {
		this.blockTable = blockTable;
	}
	
	
	
}

scrum/src/main/java/scrum/model/Colour.java
package scrum.model;

public enum Colour {
	RED(),
	YELLOW(),
	BLUE(),
	GREEN(),
	ORANGE(),
	TRANSPARENT();
	
	public String getStyle(){
		return this.name().toLowerCase();	
	}
}

scrum/src/main/java/scrum/model/CurrentGame.java
package scrum.model;

import scrum.services.CountDown;


public class CurrentGame {	
	private int currentPoints;
	private int totalPoints;
	private Level currentLevel;
	private Board board;
	private CountDown time;
	private int currentNumberOfBlocks;
	private boolean finished;
	
	public CurrentGame() {
		this.currentPoints = 0;
		this.totalPoints = 0;
		this.finished = false;
		this.currentLevel = Level.LEVEL1;			
		this.time = new CountDown(this.currentLevel.getTime());
	}	
	
	public boolean isWinner(){
		if(this.currentPoints>=this.currentLevel.getGoal()){
			return true;
		}
		return false;
	}
	
	
//	**********************************************
//	Getters and Setters

	public int getCurrentPoints() {
		return currentPoints;
	}

	public void setCurrentPoints(int currentPoints) {
		this.currentPoints = currentPoints;
	}

	public CountDown getTime() {
		return time;
	}

	public void setTime(CountDown time) {
		this.time = time;
	}

	public int getCurrentNumberOfBlocks() {
		return currentNumberOfBlocks;
	}

	public void setCurrentNumberOfBlocks(int currentNumberOfBlocks) {
		this.currentNumberOfBlocks = currentNumberOfBlocks;
	}

	public Level getCurrentLevel() {
		return currentLevel;
	}

	public Board getBoard() {
		return board;
	}

	public void setBoard(Board board) {
		this.board = board;
	}


	public boolean isFinished() {
		return finished;
	}


	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public int getTotalPoints() {
		return totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	public void setCurrentLevel(Level level) {
		this.currentLevel = level;
	}
	

}

scrum/src/main/java/scrum/model/Level.java
package scrum.model;

public enum Level {
	LEVEL1(3, 60, 1200),
	LEVEL2(3, 60, 1600),
	LEVEL3(4, 100, 1000),
	LEVEL4(4, 100, 1500),
	LEVEL5(5, 90, 1000);
	
	private int colorCount;
	private int time;
	private int goal;
	
	private Level(int colorCount, int time, int goal) {
		this.colorCount = colorCount;
		this.time = time;
		this.goal = goal;
	}
	
	public int getNumberOfLevel() {
		return Integer.parseInt(this.name().substring(5));
	}
	
	public boolean isLastLevel(){
		if(this.getNumberOfLevel()==Level.values().length){
			return true;
		}
		return false;
	}

	public int getColorCount() {
		return colorCount;
	}

	public int getTime() {
		return time;
	}

	public int getGoal() {
		return goal;
	}
}

scrum/src/main/java/scrum/controller/GameController.java
package scrum.controller;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.primefaces.context.RequestContext;

import scrum.model.Block;
import scrum.model.CurrentGame;
import scrum.model.Level;
import scrum.services.BlockMover;
import scrum.services.BlockRemover;
import scrum.services.BoardSetter;
import scrum.services.CountDown;
import scrum.services.GameStatusUpdater;

@ManagedBean
@SessionScoped
public class GameController implements Serializable{
	private static final long serialVersionUID = 1L;
	static final String REDIRECT = "?faces-redirect=true";	
	
	private CurrentGame game;
	private BoardSetter boardSetter;
	private boolean levelGoalPopupVisible;
	
	public GameController() {
		boardSetter = new BoardSetter();
	}
	
	@PostConstruct
	public void init(){
		boardSetter = new BoardSetter();
	}
	
	public String startNewGame(){
		this.game = new CurrentGame();
		this.game.setBoard(boardSetter.initializeBoardfor(game.getCurrentLevel()));
		levelGoalPopupVisible = true;
		return "game"+REDIRECT;
	}
	
	public String toIndex(){
		return "start" + REDIRECT;
	}
	
	public String cancel(){
		return "finalResult" + REDIRECT;
	}
	
	public String tosaveGame(){
		return "saveGame" + REDIRECT;
	}
	
	public String toResult(){
		if(this.game.isWinner() && !this.game.getCurrentLevel().isLastLevel()){
			return "levelResult"+REDIRECT;
		}
		return "finalResult"+REDIRECT;
	}
	
	public void onClick(Block block){		
		if(!this.game.getTime().isOver() && block.isClickable()){
			GameStatusUpdater statusUpdater = new GameStatusUpdater(game);
			BlockRemover remover = new BlockRemover();
			BlockMover mover = new BlockMover(this.game.getBoard());
			int removedBlocks = remover.removeSimilarNeighboursOf(block);
			mover.moveUpBlocks();
			boardSetter.refillBlocks();
			statusUpdater.updatePoints(removedBlocks);
			if(!checkPossibleMoves()){
				statusUpdater.finishGame();
				openDialog("gameFinished");
			}
		}		
	}
	
	private void openDialog(String dialog){
		RequestContext.getCurrentInstance().execute(dialog+".show();");
	}
	
	public void finishLevelOnTimeOut(){
		if(this.game.getTime().isOver()){
			GameStatusUpdater statusUpdater = new GameStatusUpdater(game);
			statusUpdater.finishGame();
			openDialog("gameFinished");
		}
		
	}
	
	private boolean checkPossibleMoves(){
		for (Block block : this.game.getBoard().getBlockTable()) {
			if(block.isClickable()){
				return true;
			}
		}
		return false;
	}
	
	public String startNewLevel(){
		int levelnumber = game.getCurrentLevel().getNumberOfLevel()+1;
		if (levelnumber <= Level.values().length) {
			game.setCurrentLevel(Level.valueOf("LEVEL" + levelnumber));
			this.game.setTime(new CountDown(this.game.getCurrentLevel().getTime()));
			this.game.setCurrentPoints(0);
			this.game.setFinished(false);
			this.game.setBoard(boardSetter.initializeBoardfor(game.getCurrentLevel()));
			levelGoalPopupVisible = true;
			return "game"+REDIRECT;
		}
		return "";
	}	
	
	public void hideLevelGoalPopup(){
		this.levelGoalPopupVisible = false;
	}

	public CurrentGame getGame() {
		return game;
	}

	public void setGame(CurrentGame game) {
		this.game = game;
	}

	public boolean isLevelGoalPopupVisible() {
		return levelGoalPopupVisible;
	}

	public void setLevelGoalPopupVisible(boolean levelGoalPopupVisible) {
		this.levelGoalPopupVisible = levelGoalPopupVisible;
	}

}

scrum/src/main/webapp/finalResult.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Ergebnis</title>
	<link rel="stylesheet" type="text/css" href="resources/css/style.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/text.css"/>
</h:head> 

<body>
	<h:form> 
	<div class="shrink-wrap-help-container">
		<div class="opacity-box big-text center-text shrink-wrap-help">
			<h:panelGroup rendered="#{gameController.game.currentLevel.lastLevel}">
				<h1>Herzlichen Glückwunsch!</h1>
				<h1>Alle Level abgeschlossen!</h1>
			</h:panelGroup>
			<h:panelGroup rendered="#{gameController.game.totalPoints!=0}">
				<div><h:outputText value="Du hast insgesamt #{gameController.game.totalPoints} Punkte erreicht." /></div>
			</h:panelGroup>
			<h:panelGroup rendered="#{gameController.game.totalPoints==0}">
				<div>Noch kein Level abgeschlossen.</div>
				<div>Probier's doch noch einmal!</div>
			</h:panelGroup>			
		</div>
	</div>		
		<div class="center-text">
			<p:commandButton rendered="#{gameController.game.totalPoints!=0}" action="#{gameController.tosaveGame()}" value="Speichern" styleClass="button"/>
			<p:commandButton rendered="#{gameController.game.totalPoints!=0}" value="Startseite" onclick="PF('dialog').show();" styleClass="button"/>
			<p:commandButton rendered="#{gameController.game.totalPoints==0}" value="Startseite" action="#{gameController.toIndex()}" styleClass="button"/>
		</div>
	</h:form>

	<p:dialog id="popupNewGame" modal="true" widgetVar="dialog">
		<h:form>
			<h:outputText value="Willst du das Spiel wirklich nicht speichern und zur Startseite zurück?" />
			<div class="center-text">
				<p:commandButton action="#{gameController.toIndex()}" value="Ja"/>
				<p:commandButton value="Nein" onclick="hide();"/>
			</div>
		</h:form>
	</p:dialog> 
</body> 
</html>

scrum/src/main/webapp/game.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Spiel</title>
	<link rel="stylesheet" type="text/css" href="resources/css/style.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/text.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/board.css"/>
</h:head> 
<body>
	<p:dialog id="popupLevelGoal" modal="true" widgetVar="levelGoal"
		rendered="#{gameController.levelGoalPopupVisible}" visible="#{gameController.levelGoalPopupVisible}">
		<h:form>
			<div class="center-text">
				<div class="big-text">Levelziel:</div>
				<div><h:outputText value="Erreiche #{gameController.game.currentLevel.goal} Punkte in #{gameController.game.time.countDown} Minuten!" /></div>
				<div>
					<p:commandButton value="Start" action="#{gameController.hideLevelGoalPopup()}" onclick="PF('pollTime').start();PF('pollFinishLevel').start();PF('levelGoal').hide();" styleClass="dialog-button"/>
				</div>
			</div>			
		</h:form>
	</p:dialog>
	
	<div id="game-page">	
		<div id="status" class="center-block">
			<h:outputText value="Level #{gameController.game.currentLevel.numberOfLevel}" styleClass="level-text"/>
			<h:form styleClass="shrink-wrap-help">
				<h:outputText id="time" value="Zeit: #{gameController.game.time.countDown}" styleClass="time-text"/>
				<p:poll widgetVar="pollTime" interval="1" autoStart="#{!gameController.levelGoalPopupVisible}" listener="#{gameController.game.time.decrement()}" stop="#{gameController.game.time.over}" update="time" />
				<p:poll widgetVar="pollFinishLevel" interval="1" autoStart="#{!gameController.levelGoalPopupVisible}" listener="#{gameController.finishLevelOnTimeOut()}" stop="#{gameController.game.time.over}" update=":gameFinished"/>
			</h:form>
			<h:outputText id="points" value="Punkte: #{gameController.game.currentPoints} / #{gameController.game.currentLevel.goal}" styleClass="points-text"/>
		</div>	
		
		<p:dataGrid id="board" styleClass="center-block" columns="20" value="#{gameController.game.board.blockTable}" var="block">
			<p:commandButton id="game-block" value="" action="#{gameController.onClick(block)}"
				styleClass="#{block.colour.style}" update="board,:points"/>
		</p:dataGrid>
			
		<h:form styleClass="center-text">
			<p:commandButton value="Abbrechen" onclick="PF('pollTime').stop();PF('CancelGame').show();" styleClass="button"/>
	    </h:form>
	</div>					
	
	<p:dialog id="CancelGame" modal="true" widgetVar="CancelGame">
		<h:form>
			<h:outputText value="Willst du das momentane Spiel wirklich beenden?" />
			<div class="center-text">
				<p:commandButton action="#{gameController.cancel()}" value="Ja" styleClass="dialog-button"/>
				<p:commandButton value="Nein" onclick="PF('pollTime').start();PF('CancelGame').hide();" styleClass="dialog-button"/>
			</div>
		</h:form>
	</p:dialog>
	
	<p:dialog id="gameFinished" modal="true" widgetVar="gameFinished">
		<h:form>
			<h:outputText value="Gewonnen!" rendered="#{gameController.game.winner}"/>
			<h:outputText value="Spiel zu Ende!" rendered="#{!gameController.game.winner}"/>
			<div class="center-text">
				<p:commandButton value="OK" action="#{gameController.toResult()}" styleClass="dialog-button"/>
			</div>
		</h:form>
	</p:dialog>
</body> 
</html>

scrum/src/main/webapp/introduction.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>anleitung</title>
	<link rel="stylesheet" type="text/css" href="resources/css/style.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/text.css"/>
</h:head> 
<body> 
	<div>
	<h2>Anleitung</h2>
		<div class="page-left opacity-box-introducing hight_boxes">
			<h3>Spielregeln</h3>
				<div class="instructions-page">
					Innerhalb eines bestimmten Zeitintervalls müssen immer wieder so viele gleichfarbige Blöcke wie es geht weggecklickt werden um die steigenden Levelziele in Punkten zu erreichen
				</div>
					
		</div>
		<div class="page-right opacity-box-introducing hight_boxes">
			<h3>Überblick der Levelziele</h3>
			<div class="instructions-page">
				<div>
					Level 1: Zeit: 180 Sekunden Ziel: 1000 Punkte</div>
				<div>Level 2: Zeit: 120 Sekunden Ziel: 1500 Punkte</div>
				<div>Level 3: Zeit: 100 Sekunden Ziel: 1000 Punkte</div>
				<div>Level 4: Zeit: 90 Sekunden Ziel: 1500 Punkte</div>
				<div>Level 5: Zeit: 60 Sekunden Ziel: 2000 Punkte</div>
			</div>
		</div>	
	</div>
	<div class= "center-text">
	<h:form>
				<p:commandButton value="Zurück" action="start?faces-redirect=true" styleClass="button" />
				</h:form>
				</div>

</body> 
</html>

scrum/src/main/webapp/levelResult.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Zwischenergebnis</title>
	<link rel="stylesheet" type="text/css" href="resources/css/style.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/text.css"/>
</h:head> 

<body>
	<div class="shrink-wrap-help-container"> 
		<div class="opacity-box big-text middle-text center-text shrink-wrap-help">
			<h2>Glückwunsch!</h2>
			<h:outputText value="Du hast #{gameController.game.currentPoints} Punkte" />
			<div><h:outputText value="in Level #{gameController.game.currentLevel.numberOfLevel} erreicht"/></div>
			<div>und steigst ein Level auf.</div>
			<div>Hier dein derzeitiger Zwischenstand:</div> 
			<h:outputText value="#{gameController.game.totalPoints} Punkte"/>
		</div>
	</div>
	<h:form>
		<div class="center-text">
			<p:commandButton action="#{gameController.startNewLevel()}" value="Nächstes Level" styleClass="button"/>
			<p:commandButton action="#{gameController.tosaveGame()}" value="Speichern" styleClass="button"/>
			<p:commandButton value="Startseite" onclick="PF('dialog').show();" styleClass="button"/>
		</div>
	</h:form>

	<p:dialog id="popupNewGame" modal="true" widgetVar="dialog">
		<h:form>
			<h:outputText value="Willst du das Spiel wirklich nicht speichern und zur Startseite zurück?" />
			<div class="center-text">
				<p:commandButton action="#{gameController.toIndex()}" value="Ja"/>
				<p:commandButton value="Nein" onclick="hide();"/>
			</div>
		</h:form>
	</p:dialog> 
</body> 
</html>

scrum/src/main/webapp/ranking.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Bestenliste</title>
	<link rel="stylesheet" type="text/css" href="resources/css/style.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/text.css"/>
</h:head> 
<body> 
	<h1>Bestenliste</h1>
	<div class="shrink-wrap-help-container">
		<p:dataTable styleClass="shrink-wrap-help" value="#{dBOperator.ranking}" var="item" paginator="true" rows="9" >
			<p:column headerText="Rang">
				#{item.rank}
			</p:column>
			<p:column headerText="Name"> 
				#{item.user}
			</p:column>
			<p:column headerText="Punkte">
				#{item.points}
			</p:column>
			<p:column headerText="Datum">
				#{item.date}
			</p:column>
		</p:dataTable>
	</div>
	
	<h:form>
		<div class="center-text">
			<p:commandButton value="Zur Startseite" action="start?faces-redirect=true" styleClass="button"/>
		</div>		
	</h:form>
</body> 
</html>

scrum/src/main/webapp/saveGame.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>SaveGame</title>
	<link rel="stylesheet" type="text/css" href="resources/css/style.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/text.css"/>
</h:head> 
<body>
	<h:form>
		<p:messages autoUpdate="true" />
		<div class="shrink-wrap-help-container">
			<div class="opacity-box center-text shrink-wrap-help">
				<h2>Ergebnis speichern</h2> 
				<span class="big-text">
					Name:
					<h:inputText id="username" value="#{dBOperator.game.user}" required="true" requiredMessage="Bitte gib deinen Namen an">
						<f:validateLength maximum="20" minimum="3"/>
						<f:validateRegex pattern="[a-zA-Z0-9äöüÄÖÜß]+"/>
					</h:inputText>
				</span>
				
				<div><p:commandButton action="#{dBOperator.saveGame(gameController.game)}" value="speichern" styleClass="button"/></div>
				
			</div>
		</div>
	</h:form>
</body> 
</html>

scrum/src/main/webapp/start.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"> 

<h:head>
	<title>Introseite</title>
	<link rel="stylesheet" type="text/css" href="resources/css/style.css"/>
	<link rel="stylesheet" type="text/css" href="resources/css/text.css"/>	
</h:head> 
<body> 
	<h:form>	
	<div class="middle-text">
		<h1>Introseite</h1>
		<div class="center-text">		
			<p:commandButton value="Anleitung" action="introduction?faces-redirect=true"  styleClass="button"/>
			<p:commandButton value="Spielen" action="#{gameController.startNewGame()}" styleClass="button"/>
			<p:commandButton value="Bestenliste" action="ranking?faces-redirect=true" styleClass="button"/>
		</div>
	</div>
	</h:form>
</body> 
</html>